services:
  - type: web
    name: c-quest-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false   # means you’ll set it in the dashboard
